version: '3.8'

services:
  # Web Server - User interface
  web-server:
    build: ./web-server
    ports:
      - "8080:8080"
    environment:
      - BIOREACTOR_HUB_API_URL=http://bioreactor-hub:8000
    depends_on:
      - bioreactor-hub
    volumes:
      - ./web-server/uploads_tmp:/app/uploads_tmp

  # Bioreactor Hub - Experiment forwarding service
  bioreactor-hub:
    build: ./bioreactor-hub
    ports:
      - "8000:8000"
    environment:
      - BIOREACTOR_NODE_HOST=bioreactor-node
      - BIOREACTOR_NODE_PORT=22
      - BIOREACTOR_NODE_USERNAME=pi
      - SSH_KEY_PATH=/app/ssh_keys/id_rsa
    depends_on:
      - bioreactor-node
    volumes:
      - ./bioreactor-hub/ssh_keys:/app/ssh_keys:ro

  # Bioreactor Node - Hardware interface and container management
  bioreactor-node:
    build: ./bioreactor-node
    ports:
      - "9000:9000"
    environment:
      - HARDWARE_MODE=simulation
      - LOG_LEVEL=INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./bioreactor-node/data:/app/data
    privileged: true  # Required for Docker-in-Docker

volumes:
  experiment-data:

networks:
  bioreactor-network:
    driver: bridge 
